version: '3.8'

services:
    
    mongo:
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 128M
        image: mongo
        container_name: mongo
        restart: always
        hostname: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: nexu
            MONGO_INITDB_ROOT_PASSWORD: nexusecret
            MONGO_INITDB_DATABASE: nexu
        volumes:
            - mongo_volume:/data/db
            - mongo_volume:/data/configdb
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
        networks:
            - mongo_network
            - backend_network
    mongo_express:
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.25'
                    memory: 128M
        image: mongo-express
        container_name: mongo_express
        restart: always
        ports:
            - 10084:8081
        networks:
            - mongo_network
        links:
            - mongo
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: nexu
            ME_CONFIG_MONGODB_ADMINPASSWORD: nexusecret
            ME_CONFIG_BASICAUTH_USERNAME: nexu
            ME_CONFIG_BASICAUTH_PASSWORD: secret
    nexu:
        build: challenge/.
        image: nexu/challenge:dev
        container_name: nexu
        restart: always
        ports:
            - "8080:8080"
        environment:
            - PROJECT_NAME=nexu
            - spring.profiles.active=compose
            - DB_SERVER=mongo
        networks:
            - backend_network
        links:
            - mongo
networks:
    mongo_network:
        driver: bridge
    backend_network:
        driver: bridge
volumes:
    mongo_volume: